image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - push

install_dependencies:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

test_application:
  stage: test
  script: npm test

push_image:
  image: docker:latest
  stage: push
  script:
    - docker build --build-arg GIT_COMMIT=$CI_COMMIT_SHA -t busecolak/nodejs-hello-world -t busecolak/nodejs-hello-world:$CI_JOB_ID .
    - docker push busecolak/nodejs-hello-world:$CI_JOB_ID
    - docker push busecolak/nodejs-hello-world:latest